import os
import logging
from datetime import datetime

from jinja2 import Template

logger = logging.getLogger(__name__)

REPORT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{{ dataset_name }} — Analysis Report</title>
<style>
  body { font-family: Arial, sans-serif; margin: 40px; color: #222; max-width: 900px; }
  h1 { border-bottom: 3px solid #333; padding-bottom: 10px; }
  h2 { margin-top: 40px; color: #333; border-bottom: 1px solid #ccc; padding-bottom: 6px; }
  .timestamp { color: #777; font-size: 0.9em; margin-top: -8px; }
  .summary-box { background: #f5f7fa; border-left: 4px solid #4a90d9; padding: 16px; margin: 16px 0; }
  .source-tag { display: inline-block; margin-top: 8px; font-size: 0.8em; color: #4a90d9; font-style: italic; }
  .metadata-grid { display: flex; flex-wrap: wrap; gap: 10px 30px; }
  .metadata-grid div { min-width: 160px; }
  .analysis-block { margin-bottom: 30px; padding: 16px; border: 1px solid #e0e0e0; border-radius: 6px; }
  .chart-type { display: inline-block; background: #eef3fb; color: #2a5d9f; padding: 2px 10px;
                border-radius: 12px; font-size: 0.8em; font-weight: bold; margin-bottom: 6px; }
  .chart-title { margin: 6px 0 2px 0; }
  .chart-description { color: #555; margin: 0 0 10px 0; }
  .analysis-block iframe { width: 100%; height: 460px; border: none; margin-top: 6px; }
  .insight { margin: 4px 0; }
  table { border-collapse: collapse; width: 100%; margin: 10px 0; }
  th, td { border: 1px solid #ddd; padding: 6px 10px; text-align: left; }
  th { background: #f0f0f0; }
  .significant { color: #b00020; font-weight: bold; }
  .not-significant { color: #666; }
  .ai-insight { background: #fafafa; border-left: 3px solid #999; padding: 10px 14px; margin: 8px 0 18px 0; }
  .ai-insight p { margin: 3px 0; }
</style>
</head>
<body>

<h1>{{ dataset_name }} — Data Analysis Report</h1>
<p class="timestamp">Generated on {{ generated_at }}</p>

<h2>Dataset Overview</h2>
<div class="summary-box metadata-grid">
  <div><strong>File name:</strong> {{ basic_info.get("File Name", dataset_name) }}</div>
  <div><strong>Rows:</strong> {{ basic_info.get("Rows", "N/A") }}</div>
  <div><strong>Columns:</strong> {{ basic_info.get("Columns", "N/A") }}</div>
  <div><strong>Missing values:</strong> {{ basic_info.get("Missing Values", "N/A") }}</div>
  <div><strong>Duplicate rows:</strong> {{ basic_info.get("Duplicate Rows", "N/A") }}</div>
  <div><strong>Memory usage:</strong> {{ basic_info.get("Memory Usage", "N/A") }}</div>
</div>

<h2>Executive Summary</h2>
<div class="summary-box">
  <p>{{ executive_summary or "Executive summary not yet generated." }}</p>
  {% if executive_summary %}<span class="source-tag">Generated by {{ llm_model_name }}</span>{% endif %}
</div>

<h2>Analysis Results & Insights</h2>
{% for task in plan %}
<div class="analysis-block">
  <h3>{{ task.analysis_id }} — {{ task.analysis_type | replace("_", " ") | title }}</h3>
  <p><em>{{ task.rationale }}</em></p>

  {% set chart = charts_by_id.get(task.analysis_id) %}
  {% if chart and chart.chart_path %}
    <span class="chart-type">{{ (chart.chart_type or "chart") | replace("_", " ") | title }}</span>
    <p class="chart-title"><strong>{{ chart.title or task.analysis_id }}</strong></p>
    {% if chart.reasoning %}<p class="chart-description">{{ chart.reasoning }}</p>{% endif %}
    <iframe src="{{ chart.chart_path }}" title="{{ task.analysis_id }} chart"></iframe>
  {% endif %}

  {% set insight = insights_by_id.get(task.analysis_id) %}
  {% if insight %}
    {% for line in insight.insights %}
      <p class="insight">• {{ line }}</p>
    {% endfor %}
  {% endif %}
</div>
{% endfor %}

<h2>Comparative Analysis</h2>
{% if comparative_results %}
  <table>
    <tr>
      <th>Type</th><th>Columns</th><th>Mean Diff / Range</th>
      <th>Effect Size</th><th>p-value</th><th>Significance</th>
    </tr>
    {% for c in comparative_results %}
    <tr>
      <td>{{ c.comparison_type }}</td>
      <td>
        {% if c.comparison_type == "group" %}{{ c.group_column }} vs {{ c.value_column }}
        {% else %}{{ c.date_column }} vs {{ c.value_column }} ({{ c.trend }})
        {% endif %}
      </td>
      <td>{{ c.mean_difference }}</td>
      <td>{{ c.effect_size_type }} = {{ c.effect_size }}</td>
      <td>{{ c.p_value }}</td>
      <td class="{{ 'significant' if c.is_significant else 'not-significant' }}">
        {{ "Significant" if c.is_significant else "Not significant" }}
      </td>
    </tr>
    {% endfor %}
  </table>

  {% for c in comparative_results %}
    {% if c.ai_insight %}
    <div class="ai-insight">
      <p><strong>{{ c.comparison_id or loop.index }}:</strong> {{ c.ai_insight.summary }}</p>
      <p><strong>Business impact:</strong> {{ c.ai_insight.business_impact }}</p>
      <p><strong>Recommendation:</strong> {{ c.ai_insight.recommendation }}</p>
    </div>
    {% endif %}
  {% endfor %}
{% else %}
  <p>No comparative analyses were applicable to this dataset.</p>
{% endif %}

<h2>Final Conclusions</h2>
<div class="summary-box">
  <p>{{ final_conclusions }}</p>
  {% if conclusions_source == "llm" %}<span class="source-tag">Generated by {{ llm_model_name }}</span>{% endif %}
</div>

</body>
</html>
"""


class ReportBuilder:

    def __init__(self, output_dir="outputs/reports", llm=None):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)
        self.llm_model_name = "Gemini 3.5 Flash"
        self.llm = llm or self._default_llm()

    def _default_llm(self):
        try:
            from dotenv import load_dotenv
            from langchain_google_genai import ChatGoogleGenerativeAI
            load_dotenv()
            return ChatGoogleGenerativeAI(model="gemini-3.5-flash", temperature=0)
        except Exception:
            return None

    # ---- normalization ----

    @staticmethod
    def _to_dict(obj):
        """Normalize a single record (dict, Pydantic model, or any plain
        object) to a plain dict. Anything already dict-like passes through
        unchanged; Pydantic v2/v1 models are dumped via their own methods;
        arbitrary objects fall back to their __dict__. If none of that
        applies, the object is returned as-is (the template's forgiving
        `.` lookups will still degrade gracefully via Undefined)."""
        if isinstance(obj, dict):
            return obj
        if hasattr(obj, "model_dump"):      # pydantic v2
            return obj.model_dump()
        if hasattr(obj, "dict"):            # pydantic v1
            return obj.dict()
        if hasattr(obj, "__dict__"):
            return vars(obj)
        return obj

    @classmethod
    def _normalize_records(cls, records):
        return [cls._to_dict(r) for r in (records or [])]

    def build_report(self, dataset_name, profile, plan, chart_results,
                      insight_results, comparative_results, executive_summary=None):
        logger.info("Building HTML report for dataset '%s'", dataset_name)

        # Normalize every upstream record to a plain dict up front, so the
        # dict comprehensions below (bare `[...]` subscripting, which has
        # none of Jinja's attribute-then-item fallback) never blow up on a
        # Pydantic model or other non-dict object from an upstream agent.
        plan = self._normalize_records(plan)
        chart_results = self._normalize_records(chart_results)
        insight_results = self._normalize_records(insight_results)
        comparative_results = self._normalize_records(comparative_results)

        charts_by_id = {c["analysis_id"]: c for c in chart_results}
        insights_by_id = {i["analysis_id"]: i for i in insight_results}

        final_conclusions, conclusions_source = self._build_final_conclusions(
            plan, comparative_results, insight_results, executive_summary
        )

        template = Template(REPORT_TEMPLATE)
        html = template.render(
            dataset_name=dataset_name,
            generated_at=datetime.now().strftime("%d %B %Y, %I:%M %p"),
            basic_info=self._to_dict(profile).get("basic_info", {}) if profile else {},
            executive_summary=executive_summary,
            llm_model_name=self.llm_model_name,
            plan=plan,
            charts_by_id=charts_by_id,
            insights_by_id=insights_by_id,
            comparative_results=comparative_results,
            final_conclusions=final_conclusions,
            conclusions_source=conclusions_source,
        )

        logger.info("Writing HTML report to disk")
        html_path = os.path.join(self.output_dir, f"{dataset_name}_report.html")
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html)
        logger.info("HTML report generated at %s", html_path)

        pdf_path = self._export_pdf(html, dataset_name)
        if pdf_path:
            logger.info("PDF report generated at %s", pdf_path)
        else:
            logger.info("PDF export skipped (unavailable in this environment)")

        return {"html_path": html_path, "pdf_path": pdf_path}

    # ---- AI-generated closing conclusions ----

    def _build_final_conclusions(self, plan, comparative_results, insight_results, executive_summary):
        n_significant = sum(1 for c in comparative_results if c.get("is_significant"))

        if self.llm is not None:
            try:
                insight_lines = [
                    f"{i['analysis_id']}: " + "; ".join(i.get("insights", []))
                    for i in insight_results
                ]
                comparison_lines = [
                    c.get("ai_insight", {}).get("summary", "")
                    for c in comparative_results
                    if c.get("ai_insight")
                ]
                prompt = f"""
You are a senior data analyst writing the closing section of an automated
data analysis report.

Executive summary already given to the reader: {executive_summary or "N/A"}

Number of analyses run: {len(plan)}
Per-analysis insights: {insight_lines}

Number of comparative tests run: {len(comparative_results)}
({n_significant} statistically significant)
Comparative interpretations: {comparison_lines}

Write exactly 3 concise concluding paragraphs for a business reader:
1) What the data shows overall.
2) The most important statistically-backed finding(s) and their practical
   significance (not just p-values).
3) Recommended next steps.
Do not repeat the executive summary verbatim. Do not use bullet points —
write in full paragraphs.
"""
                response = self.llm.invoke(prompt)
                text = getattr(response, "content", None) or str(response)
                if text.strip():
                    return text.strip(), "llm"
            except Exception as e:
                logger.error("LLM error generating final conclusions: %s", e)

        fallback = (
            f"This report was generated automatically. {len(plan)} analyses were run, "
            f"{len(comparative_results)} comparative tests were performed "
            f"({n_significant} statistically significant)."
        )
        return fallback, "fallback"

    # ---- optional PDF export ----

    def _export_pdf(self, html, dataset_name):
        """Best-effort HTML -> PDF conversion. Skips gracefully if weasyprint
        (or its system dependencies) aren't available in this environment."""
        try:
            from weasyprint import HTML
        except Exception as e:
            logger.info("weasyprint not available, skipping PDF export: %s", e)
            return None

        try:
            pdf_path = os.path.join(self.output_dir, f"{dataset_name}_report.pdf")
            HTML(string=html, base_url=self.output_dir).write_pdf(pdf_path)
            return pdf_path
        except Exception as e:
            logger.error("PDF export failed, continuing with HTML only: %s", e)
            return None